//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDo.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToDo.Domain.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request is bad.
        /// </summary>
        public static string Application_BadRequest {
            get {
                return ResourceManager.GetString("Application.BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a conflict with the current state of the resource..
        /// </summary>
        public static string Application_Conflict {
            get {
                return ResourceManager.GetString("Application.Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to this resource is forbidden..
        /// </summary>
        public static string Application_Forbidden {
            get {
                return ResourceManager.GetString("Application.Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred. Please try again later..
        /// </summary>
        public static string Application_InternalServerError {
            get {
                return ResourceManager.GetString("Application.InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found..
        /// </summary>
        public static string Application_NotFound {
            get {
                return ResourceManager.GetString("Application.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is temporarily unavailable. Please try again later..
        /// </summary>
        public static string Application_ServiceUnavailable {
            get {
                return ResourceManager.GetString("Application.ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Application_Success {
            get {
                return ResourceManager.GetString("Application.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have sent too many requests. Please wait and try again..
        /// </summary>
        public static string Application_TooManyRequests {
            get {
                return ResourceManager.GetString("Application.TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request is not authorized.
        /// </summary>
        public static string Application_Unauthorized {
            get {
                return ResourceManager.GetString("Application.Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be processed..
        /// </summary>
        public static string Application_UnprocessableEntity {
            get {
                return ResourceManager.GetString("Application.UnprocessableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occurred..
        /// </summary>
        public static string Application_Validation {
            get {
                return ResourceManager.GetString("Application.Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit not found..
        /// </summary>
        public static string Authority_AuditNotFound {
            get {
                return ResourceManager.GetString("Authority.AuditNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority media not found..
        /// </summary>
        public static string Authority_AuthorityMediaNotFound {
            get {
                return ResourceManager.GetString("Authority.AuthorityMediaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch not found..
        /// </summary>
        public static string Authority_BranchNotFound {
            get {
                return ResourceManager.GetString("Authority.BranchNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory already exists..
        /// </summary>
        public static string Authority_DirectoryAlreadyExists {
            get {
                return ResourceManager.GetString("Authority.DirectoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory not found..
        /// </summary>
        public static string Authority_DirectoryNotFound {
            get {
                return ResourceManager.GetString("Authority.DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History already exists..
        /// </summary>
        public static string Authority_HistoryAlreadyExists {
            get {
                return ResourceManager.GetString("Authority.HistoryAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History not found..
        /// </summary>
        public static string Authority_HistoryNotFound {
            get {
                return ResourceManager.GetString("Authority.HistoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid audit snapshot..
        /// </summary>
        public static string Authority_InvalidAuditSnapshot {
            get {
                return ResourceManager.GetString("Authority.InvalidAuditSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media not found..
        /// </summary>
        public static string Authority_MediaNotFound {
            get {
                return ResourceManager.GetString("Authority.MediaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority not found or you don&apos;t have permission to view it..
        /// </summary>
        public static string Authority_NotFound {
            get {
                return ResourceManager.GetString("Authority.NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President already exists..
        /// </summary>
        public static string Authority_PresidentAlreadyExists {
            get {
                return ResourceManager.GetString("Authority.PresidentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President not found.
        /// </summary>
        public static string Authority_PresidentNotFound {
            get {
                return ResourceManager.GetString("Authority.PresidentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social media link not found..
        /// </summary>
        public static string Authority_SocialMediaLinkNotFound {
            get {
                return ResourceManager.GetString("Authority.SocialMediaLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url must be a valid URI.
        /// </summary>
        public static string Er_Url_must_be__avalid_URI {
            get {
                return ResourceManager.GetString("Er_Url_must_be_ avalid_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddressAr must not exceed 500 characters.
        /// </summary>
        public static string Err_AddressAr_must_not_exceed_500_characters {
            get {
                return ResourceManager.GetString("Err_AddressAr_must_not_exceed_500_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform must not exceed 100 characters.
        /// </summary>
        public static string Err_AddressEn_must_not_exceed_500_characters {
            get {
                return ResourceManager.GetString("Err_AddressEn_must_not_exceed_500_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Least One Description Required.
        /// </summary>
        public static string ERR_ATLEASTONEDESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_ATLEASTONEDESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Least One Description Required.
        /// </summary>
        public static string ERR_ATLEASTONETITLE_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_ATLEASTONETITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches must not be empty..
        /// </summary>
        public static string Err_Branches_must_not_be_empty_ {
            get {
                return ResourceManager.GetString("Err_Branches_must_not_be_empty.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts must not be null.
        /// </summary>
        public static string Err_Contacts_must_not_be_null {
            get {
                return ResourceManager.GetString("Err_Contacts_must_not_be_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must contain Arabic content ..
        /// </summary>
        public static string ERR_DESCRIPTION_ARABIC_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_DESCRIPTION_ARABIC_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description must contain English content if Arabic content is not provided.
        /// </summary>
        public static string ERR_DESCRIPTION_ENGLISH_REQUIRED {
            get {
                return ResourceManager.GetString("ERR_DESCRIPTION_ENGLISH_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionEn must not exceed 1000 characters.
        /// </summary>
        public static string Err_DescriptionAr_must_not_exceed_1000_characters {
            get {
                return ResourceManager.GetString("Err_DescriptionAr_must_not_exceed_1000_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DescriptionEn must not exceed 1000 characters.
        /// </summary>
        public static string Err_DescriptionEn_must_not_exceed_1000_characters {
            get {
                return ResourceManager.GetString("Err_DescriptionEn_must_not_exceed_1000_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string Err_Email_is_required {
            get {
                return ResourceManager.GetString("Err_Email_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapLink must not exceed 500 characters.
        /// </summary>
        public static string Err_Email_must_be_avalid_email_address {
            get {
                return ResourceManager.GetString("Err_Email_must_be_avalid_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Server.
        /// </summary>
        public static string Err_Error_Server {
            get {
                return ResourceManager.GetString("Err_Error_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Title and Description must be in the same language (both Arabic or both English)..
        /// </summary>
        public static string ERR_LANGUAGE_CONSISTENCY {
            get {
                return ResourceManager.GetString("ERR_LANGUAGE_CONSISTENCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapLink is required.
        /// </summary>
        public static string Err_MapLink_is_required {
            get {
                return ResourceManager.GetString("Err_MapLink_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MapLink must not exceed 500 characters.
        /// </summary>
        public static string Err_MapLink_must_not_exceed_500_characters {
            get {
                return ResourceManager.GetString("Err_MapLink_must_not_exceed_500_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Must not be null .
        /// </summary>
        public static string ErrDescriptionNull {
            get {
                return ResourceManager.GetString("ErrDescriptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title Must not be null.
        /// </summary>
        public static string ErrTitleNull {
            get {
                return ResourceManager.GetString("ErrTitleNull", resourceCulture);
            }
        }
    }
}
